import { chromium } from '@playwright/test';
const browser = await chromium.launch({headless:true,args:['--no-sandbox']});
const page = await browser.newPage({viewport:{width:1440,height:1080}});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto('http://localhost:5173',{waitUntil:'networkidle'});
await page.screenshot({path:'/tmp/teachhelper-desktop.png',fullPage:true});
await page.getByRole('button',{name:'Продолжить занятие'}).click();
await page.getByRole('button',{name:'Оценка Александров Артём: —. Изменить',exact:true}).click();
await page.getByRole('button',{name:'Оценка Александров Артём: 0. Изменить',exact:true}).click();
await page.getByRole('button',{name:'Закрыть окно',exact:true}).click();
await page.reload();
await page.getByRole('button',{name:'Продолжить занятие'}).click();
if(await page.getByRole('button',{name:'Оценка Александров Артём: 5. Изменить',exact:true}).count()!==1)throw Error('Grade persistence failed');
await page.getByRole('button',{name:'Закрыть окно',exact:true}).click();
await page.getByRole('button',{name:'Добавить группу Новая группа студентов'}).click();
await page.getByLabel('Название группы').fill('ТЕСТ-01');
await page.getByLabel('Специальность').fill('Тестирование');
await page.getByRole('button',{name:'Создать группу',exact:true}).click();
await page.getByRole('button',{name:'Экспорт ведомости Скачать в формате Excel'}).click();
const download=page.waitForEvent('download');
await page.getByRole('button',{name:'Скачать ведомость',exact:true}).click();
if(!(await download).suggestedFilename().endsWith('.xlsx'))throw Error('Excel export failed');
await page.setViewportSize({width:360,height:800});
await page.screenshot({path:'/tmp/teachhelper-mobile.png',fullPage:true});
if(await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth))throw Error('Mobile horizontal overflow');
await page.getByRole('button',{name:'Продолжить занятие'}).click();
await page.screenshot({path:'/tmp/teachhelper-journal.png',fullPage:true});
if(await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth))throw Error('Journal horizontal overflow');
await page.getByRole('button',{name:'Закрыть окно',exact:true}).click();
await page.locator('.bottom-nav').getByRole('button',{name:'Расписание',exact:true}).click();
await page.getByRole('button',{name:'Вт 15',exact:true}).click();
if(await page.locator('.lesson-card').count()!==2)throw Error('Schedule date filter failed');
await browser.close();
if(errors.length)throw Error(errors.join('\n'));
console.log('PASS: desktop, 360px mobile, grade persistence, group creation, Excel download, day filtering, no runtime errors.');
