import { useEffect, useRef, useState, type FormEvent, type ReactNode } from 'react';
import Icon, { type IconName } from './components/Icon';
import { TODAY, initialGroups, initialLessons, studentNames, subjects, loadLocal, saveLocal, dateLabel, isoDate, type Lesson, type Group } from './data';
import { downloadExcel, downloadBlob } from './export';
import { fetchGroups, fetchStudents, fetchSubjects, fetchTodaySchedule, createGroupApi, createLessonApi, fetchAttendance, postAttendanceBulk, postBackup, gradeFromDb, downloadServerXlsx, TIME_SLOTS } from './api';

type Page = 'Сегодня' | 'Расписание' | 'Группы' | 'Предметы' | 'Журнал' | 'Отчёты' | 'Настройки';
type Modal = 'lesson' | 'newLesson' | 'newGroup' | 'export' | 'help' | 'notifications' | 'calendar' | 'group' | null;
const nav: {label: Page; icon: IconName}[] = [{label:'Сегодня',icon:'sun'},{label:'Расписание',icon:'calendar'},{label:'Группы',icon:'users'},{label:'Предметы',icon:'book'},{label:'Журнал',icon:'journal'},{label:'Отчёты',icon:'chart'}];
const weekdays = ['Пн','Вт','Ср','Чт','Пт','Сб','Вс'];
const gradeValues = ['—', '0', '5', '4', '3', '2'];
function Button({children, onClick, variant = 'primary', className = '', type = 'button'}: {children: ReactNode; onClick?: () => void; variant?: string; className?: string; type?: 'button'|'submit'}) {return <button type={type} className={'btn btn-'+variant+' '+className} onClick={onClick}>{children}</button>}

export default function App() {
 const [page, setPage] = useState<Page>('Сегодня');
 const [lessons, setLessons] = useState<Lesson[]>(() => loadLocal('lessons', initialLessons));
 const [groups, setGroups] = useState<Group[]>(() => loadLocal('groups', initialGroups));
 const [grades, setGrades] = useState<Record<string,string>>(() => loadLocal('grades', {}));
 const [date, setDate] = useState(TODAY);
 const [weekOffset, setWeekOffset] = useState(0);
 const [modal, setModal] = useState<Modal>(null);
 const [selectedLesson, setSelectedLesson] = useState<Lesson | null>(null);
 const [selectedGroup, setSelectedGroup] = useState<Group | null>(null);
 const [query, setQuery] = useState('');
 const [groupFilter, setGroupFilter] = useState('Все группы');
 const [toast, setToast] = useState('');
 const [menu, setMenu] = useState(false);
 const [notificationRead, setNotificationRead] = useState(false);
 const [profile, setProfile] = useState(() => loadLocal('profile', {name:'Александр Сергеевич', initials:'АС'}));
 const [compact, setCompact] = useState(() => loadLocal('compact', false));
 const [exportGroup, setExportGroup] = useState('ИС-21');
 const [exportDate, setExportDate] = useState(TODAY);
 const [studentQuery, setStudentQuery] = useState('');
 const [formError, setFormError] = useState('');
 const [calendarMonth, setCalendarMonth] = useState(8);
 const toastTimer = useRef<ReturnType<typeof setTimeout> | null>(null);
 const modalRef = useRef<HTMLDivElement>(null);
 const [loading, setLoading] = useState(true);
 const [apiOk, setApiOk] = useState(true);
 const [nameToId, setNameToId] = useState<Record<string, number>>({});
 const [realSubjects, setRealSubjects] = useState<{id: number; name: string; total_hours: number; group_id: number; group_name: string; held_lessons: number; remaining: number}[]>([]);
 const [lessonStudents, setLessonStudents] = useState<{id: number; name: string}[]>([]);
 function notify(message: string) { setToast(message); if(toastTimer.current) clearTimeout(toastTimer.current); toastTimer.current = setTimeout(() => setToast(''), 3500); }
 function navigate(next: Page) {setPage(next); setMenu(false); setQuery(''); window.scrollTo(0,0);}
 function openModal(next: Modal) {setFormError(''); setStudentQuery(''); setModal(next);}
 function openLesson(lesson: Lesson) {setSelectedLesson(lesson);openModal('lesson');if(apiOk&&lesson.id){fetchAttendance(lesson.id).then(data=>{const studs=data.students.map(s=>({id:s.id,name:s.last_name+' '+s.first_name}));setLessonStudents(studs);const next={...grades};const n2iUpdate={...nameToId};data.attendance.forEach(a=>{const nm=a.last_name+' '+a.first_name;n2iUpdate[nm]=a.student_id;next[lesson.id+':'+nm]=gradeFromDb(a.grade)});setNameToId(n2iUpdate);setGrades(next)}).catch(()=>{setLessonStudents(studentNames.slice(0,lesson.students).map(n=>({id:0,name:n})))})}else{setLessonStudents(studentNames.slice(0,lesson.students).map(n=>({id:0,name:n})))}}
 function persistLessons(next: Lesson[]) {setLessons(next); if(!saveLocal('lessons',next)) notify('Не удалось сохранить: память браузера недоступна');}
 useEffect(() => { if (!modal) return; const previous = document.activeElement as HTMLElement; const old = document.body.style.overflow; document.body.style.overflow = 'hidden'; const el = modalRef.current; const focusable = () => el?.querySelectorAll<HTMLElement>('button, input, select, textarea, [tabindex="0"]'); focusable()?.[0]?.focus(); const onKey = (e: KeyboardEvent) => {if(e.key === 'Escape') setModal(null); if(e.key === 'Tab') {const all = focusable(); if(!all?.length) return; const first=all[0], last=all[all.length-1]; if(e.shiftKey && document.activeElement===first) {e.preventDefault();last.focus();} else if(!e.shiftKey && document.activeElement===last){e.preventDefault();first.focus();}}}; document.addEventListener('keydown',onKey); return () => {document.body.style.overflow=old; document.removeEventListener('keydown',onKey);previous?.focus();}; },[modal]);
 // ─── Load real data from API on mount ───────────────────────
 useEffect(() => {
   let cancelled = false;
   (async () => {
     try {
       const [apiGroups, apiSubjects, todayData] = await Promise.all([fetchGroups(), fetchSubjects(), fetchTodaySchedule()]);
       if (cancelled) return;
       const newGroups: Group[] = [];
       const allStudents: {id: number; name: string; groupId: number}[] = [];
       const n2i: Record<string, number> = {};
       const colors = ['green', 'blue', 'purple', 'orange'];
       for (const g of apiGroups) {
         const studs = await fetchStudents(g.id);
         const gs = studs.map(s => ({ id: s.id, name: s.last_name + ' ' + s.first_name, groupId: g.id }));
         gs.forEach(s => { n2i[s.name] = s.id; });
         allStudents.push(...gs);
         const groupSubs = apiSubjects.filter(s => s.group_id === g.id);
         newGroups.push({ id: g.id, name: g.name, course: groupSubs[0]?.group_name || g.name, students: studs.length, subjects: groupSubs.length, color: colors[newGroups.length % colors.length] });
       }
       const newLessons: Lesson[] = todayData.lessons.map((l) => {
         const num = (l.lesson_number as number) || 1;
         const times = TIME_SLOTS[num] || TIME_SLOTS[1];
         return { id: l.id, title: l.actual_subject_name || l.planned_subject || '', group: l.group_name || '', room: '—', start: times.start, end: times.end, date: l.date || todayData.date, status: l.status === 'held' ? 'done' as const : 'upcoming' as const, type: 'Практическое занятие', students: allStudents.filter(s => s.groupId === l.group_id).length };
       });
       if (!cancelled) { setGroups(newGroups); setLessons(newLessons); setNameToId(n2i); setRealSubjects(apiSubjects); setApiOk(true); }
     } catch (e) { console.warn('API unavailable, using local data:', e); if (!cancelled) setApiOk(false); } finally { if (!cancelled) setLoading(false); }
   })();
   return () => { cancelled = true; };
 }, []);
 const todayLessons = lessons.filter(l => l.date === TODAY);
 const dayLessons = lessons.filter(l => l.date === date && (groupFilter === 'Все группы' || l.group === groupFilter) && (l.title+' '+l.group).toLowerCase().includes(query.toLowerCase())).sort((a,b) => a.start.localeCompare(b.start));
 const visibleGroups = groups.filter(g => (g.name+' '+g.course).toLowerCase().includes(query.toLowerCase()));
 const weekDates = Array.from({length:7},(_,i) => {const d = new Date(TODAY+'T12:00:00'); d.setDate(d.getDate()+weekOffset*7+i); return isoDate(d)});
 const doneCount = todayLessons.filter(l=>l.status==='done').length;
 function saveGrade(student: string, grade: string) {if(!selectedLesson) return; const next = {...grades, [selectedLesson.id+':'+student]:grade}; setGrades(next); if(!saveLocal('grades',next)) notify('Не удалось сохранить оценку'); if(apiOk) { const sid = nameToId[student]; if(selectedLesson.id && sid) { postAttendanceBulk(selectedLesson.id, [{student_id: sid, grade}]).catch(()=>{}); } } }
 function cycleGrade(student: string, direction: number) { const current = grades[selectedLesson!.id+':'+student] || '—'; saveGrade(student,gradeValues[(gradeValues.indexOf(current)+direction+gradeValues.length)%gradeValues.length]); }
 function createLesson(e: FormEvent<HTMLFormElement>) {e.preventDefault(); const f=new FormData(e.currentTarget); const start=String(f.get('start')), end=String(f.get('end')); if(end<=start){setFormError('Время окончания должно быть позже начала.');return;} const lessonDate=String(f.get('date')); if(lessonDate>TODAY){setFormError('Начать занятие можно сегодня или прошедшей датой.');return;} const group=groups.find(g=>g.name===f.get('group'))!; const subjectName=String(f.get('subject')); const mkLesson=(lid:number):Lesson=>({id:lid,title:subjectName,group:group.name,room:String(f.get('room')||'—'),start,end,date:lessonDate,status:'active',type:String(f.get('type')),students:group.students}); if(apiOk){const subj=realSubjects.find(s=>s.name===subjectName);if(subj){createLessonApi(subj.id,lessonDate).then(r=>{const next=mkLesson(r.id);persistLessons([...lessons,next]);setSelectedLesson(next);setDate(lessonDate);setModal('lesson');notify('Занятие начато')}).catch(()=>{const next=mkLesson(Date.now());persistLessons([...lessons,next]);setSelectedLesson(next);setDate(lessonDate);setModal('lesson');notify('Занятие создано локально')});return;}} const next=mkLesson(Date.now());persistLessons([...lessons,next]);setSelectedLesson(next);setDate(lessonDate);setModal('lesson');notify('Занятие начато')}
 function createGroup(e: FormEvent<HTMLFormElement>) {e.preventDefault();const f=new FormData(e.currentTarget);const name=String(f.get('name')).trim();if(!name){setFormError('Введите название группы.');return;}if(groups.some(g=>g.name.toLowerCase()===name.toLowerCase())){setFormError('Группа с таким названием уже существует.');return;}const mkGroup=(gid:number):Group=>({id:gid,name,course:String(f.get('course'))+' курс · '+String(f.get('specialty')),students:0,subjects:0,color:'green'});if(apiOk){createGroupApi(name).then(r=>{const next=[...groups,mkGroup(r.id)];setGroups(next);saveLocal('groups',next);setModal(null);notify('Группа '+name+' создана')}).catch(()=>{const next=[...groups,mkGroup(Date.now())];setGroups(next);saveLocal('groups',next);setModal(null);notify('Группа создана локально')});return;}const next=[...groups,mkGroup(Date.now())];setGroups(next);saveLocal('groups',next);setModal(null);notify('Группа '+name+' создана')}
 function exportReport() {if(apiOk){const subj=realSubjects.find(s=>s.name===exportGroup||s.group_name===exportGroup);if(subj){downloadServerXlsx(subj.id).then(blob=>{downloadBlob(blob,'Ведомость_'+exportGroup+'_'+exportDate);setModal(null);notify('Excel-файл скачан')}).catch(()=>{exportReportLocal()});return;}}exportReportLocal();function exportReportLocal(){const selected=lessons.filter(l=>l.group===exportGroup && l.date<=exportDate);const count=groups.find(g=>g.name===exportGroup)?.students||0;const rows:(string|number)[][]=[['Ведомость',exportGroup],['По состоянию на',dateLabel(exportDate)],['Студент',...selected.map(l=>l.title+' · '+dateLabel(l.date))],...studentNames.slice(0,count).map(s=>[s,...selected.map(l=>grades[l.id+':'+s]||'—')])];downloadExcel(rows,'Ведомость_'+exportGroup+'_'+exportDate);setModal(null);notify('Excel-файл подготовлен для скачивания')}}
 function renderLesson(l: Lesson, index: number) {return <article key={l.id} className={'lesson-card '+(l.status==='active'?'lesson-active':'')}><div className="lesson-time"><strong>{l.start}</strong><span>{l.end}</span><small>{index+1} пара</small></div><div className="lesson-body"><div className="lesson-title-row"><h3>{l.title}</h3><span className={'status status-'+l.status}>{l.status==='done'?<><Icon name="check" size={12}/>Проведено</>:l.status==='active'?<><span className="live-dot"/>Сейчас</>:'Далее'}</span></div><div className="lesson-meta"><span className="group-tag"><Icon name="users" size={13}/>{l.group}</span><span className="meta-dot">·</span><span>Каб. {l.room}</span><span className="meta-dot">·</span><span className="lesson-type">{l.type}</span></div><div className="lesson-bottom"><span><Icon name={l.status==='done'?'check-circle':'users'} size={14}/>{l.status==='done'?'Посещаемость отмечена':l.students+' студента'}</span><button className={'lesson-link '+(l.status==='active'?'active-link':'')} onClick={()=>openLesson(l)}>{l.status==='done'?'Открыть журнал':l.status==='active'?'Продолжить занятие':'Открыть занятие'}<Icon name="arrow" size={15}/></button></div></div></article>}
 function renderGroup(g: Group) {return <button key={g.id} className="group-card" onClick={()=>{setSelectedGroup(g);openModal('group')}}><div className="group-card-top"><span className={'icon-box '+g.color}><Icon name="users" size={21}/></span><Icon name="chevron" size={16}/></div><h3>{g.name}</h3><p>{g.course}</p><div className="group-card-footer"><span><Icon name="users" size={14}/>{g.students} студента</span><span>{g.subjects} предмета</span></div></button>}
 const schedulePanel = <section className="schedule-panel"><div className="section-heading"><h2>{page==='Расписание'?'Расписание занятий':'Занятия на сегодня'}<span className="count">{dayLessons.length}</span></h2><button className="text-link" onClick={()=>{if(page==='Расписание')openModal('calendar');else navigate('Расписание')}}>{page==='Расписание'?'Выбрать дату':'Всё расписание'}<Icon name="arrow" size={16}/></button></div><div className="panel schedule-inner"><div className="week-heading"><button className="month-button" onClick={()=>openModal('calendar')}><Icon name="calendar" size={17}/>{dateLabel(weekDates[0],{month:'long',year:'numeric'}).replace(' г.','')}<Icon name="chevron" size={13} className="rotate-down"/></button><div className="week-arrows"><button aria-label="Предыдущая неделя" onClick={()=>{setWeekOffset(weekOffset-1);const d=new Date(weekDates[0]+'T12:00:00');d.setDate(d.getDate()-7);setDate(isoDate(d));}}><Icon name="left" size={16}/></button><button aria-label="Следующая неделя" onClick={()=>{setWeekOffset(weekOffset+1);const d=new Date(weekDates[0]+'T12:00:00');d.setDate(d.getDate()+7);setDate(isoDate(d));}}><Icon name="chevron" size={16}/></button></div></div><div className="week-strip">{weekDates.map((d,i)=><button key={d} className={'week-day '+(d===date?'selected ':'')+(i>4?'weekend':'')} onClick={()=>setDate(d)}><span>{weekdays[i]}</span><strong>{Number(d.slice(8))}</strong><i className={lessons.some(l=>l.date===d)?'has-lessons':''}/></button>)}</div><div className="day-label"><span>{date===TODAY?'Сегодня':dateLabel(date,{weekday:'long'})}, {dateLabel(date)}</span><span>{date===TODAY?'Чётная неделя':weekOffset%2===0?'Чётная неделя':'Нечётная неделя'}</span></div><div className="lesson-list">{dayLessons.length?dayLessons.map(renderLesson):<div className="empty-state"><Icon name="sun" size={32}/><h3>Занятий нет</h3><p>На этот день ничего не запланировано.</p><button className="text-link" onClick={()=>{setDate(TODAY);setWeekOffset(0);setGroupFilter('Все группы');setQuery('')}}>Вернуться к сегодняшнему дню <Icon name="arrow" size={16}/></button></div>}</div><div className="schedule-footer"><Icon name="clock" size={14}/><span>{dayLessons.length} занятия · {dayLessons.length*2} академических часов</span><span className="footer-dot">·</span><span>{new Set(dayLessons.map(l=>l.group)).size} группы</span></div></div></section>;
 return <div className={'app '+(compact?'compact':'')}>
 {loading&&<div style={{position:'fixed',top:0,left:0,right:0,height:3,background:'linear-gradient(90deg,#22c55e,#3b82f6)',zIndex:9999,animation:'pulse 1.5s ease-in-out infinite'}}/>}
 {menu&&<div className="sidebar-scrim" onClick={()=>setMenu(false)}/>}
 <aside className={'sidebar '+(menu?'sidebar-open':'')}><a className="brand" href="#" onClick={e=>{e.preventDefault();navigate('Сегодня')}}><span className="brand-icon"><Icon name="book" size={24}/></span><span>Teach<span className="brand-light">Helper</span><small>Журнал преподавателя</small></span></a><div className="workspace-label">РАБОЧЕЕ ПРОСТРАНСТВО</div><nav className="main-nav">{nav.map(n=><button key={n.label} className={page===n.label?'nav-item selected':'nav-item'} onClick={()=>navigate(n.label)}><Icon name={n.icon}/><span>{n.label}</span>{n.label==='Сегодня'&&<span className="nav-count">{todayLessons.length}</span>}</button>)}</nav><div className="sidebar-bottom"><nav><button className={'nav-item '+(page==='Настройки'?'selected':'')} onClick={()=>navigate('Настройки')}><Icon name="settings"/><span>Настройки</span></button><button className="nav-item" onClick={()=>openModal('help')}><Icon name="help"/><span>Помощь и поддержка</span></button></nav><div className="local-note"><span className="local-symbol"><Icon name="shield" size={19}/></span><div><strong>Всё под вашим контролем</strong><p>Данные хранятся на устройстве.<br/>Работайте в своём ритме.</p></div></div><button className="sidebar-profile" onClick={()=>navigate('Настройки')}><span className="avatar">{profile.initials}</span><span><strong>{profile.name.split(' ')[0]} {profile.name.split(' ')[1]?.[0]}.</strong><small>Преподаватель</small></span><Icon name="more" size={18}/></button></div></aside>
 <div className="main-shell"><header className="topbar"><div className="breadcrumb"><button className="mobile-menu icon-button" onClick={()=>setMenu(!menu)} aria-label="Открыть меню"><Icon name="menu"/></button><span className="breadcrumb-home">Рабочее пространство</span><Icon name="chevron" size={13} className="breadcrumb-chevron"/><strong>{page}</strong></div><div className="topbar-right"><span className="semester"><span className="green-dot"/>2026 / 2027 учебный год</span><span className="topbar-divider"/><button className="icon-button notification-button" onClick={()=>{openModal('notifications');setNotificationRead(true)}} aria-label="Уведомления"><Icon name="bell"/>{!notificationRead&&<i/>}</button><button className="avatar top-avatar" aria-label="Профиль преподавателя" onClick={()=>navigate('Настройки')}>{profile.initials}</button></div></header>
 <main><div className="page-heading"><div><div className="eyebrow">{page==='Сегодня'?'ПОНЕДЕЛЬНИК, 14 СЕНТЯБРЯ 2026': 'ВАШЕ РАБОЧЕЕ ПРОСТРАНСТВО'}</div><h1>{page==='Сегодня'?<>Хорошего дня, {profile.name.split(' ')[0]}<span className="greeting-sun"><Icon name="sun" size={30}/></span></>:page}</h1><p>{page==='Сегодня'?'Всё, что нужно для продуктивного учебного дня.':page==='Расписание'?'Планируйте день и держите занятия под рукой.':page==='Группы'?'Ваши студенты, предметы и успеваемость в одном месте.':page==='Журнал'?'Отмечайте посещаемость и выставляйте оценки.':page==='Предметы'?'Учебные дисциплины и ход образовательной программы.':page==='Отчёты'?'Наглядные итоги и ведомости для ваших групп.':'Настройте рабочее пространство под себя.'}</p></div>{page!=='Настройки'&&<Button onClick={()=>openModal(page==='Группы'?'newGroup':page==='Отчёты'?'export':'newLesson')}><Icon name={page==='Отчёты'?'download':'plus'} size={19}/>{page==='Группы'?'Добавить группу':page==='Отчёты'?'Экспорт в Excel':'Начать занятие'}</Button>}</div>
 {(page==='Сегодня'||page==='Отчёты')&&<div className="stats-grid"><div className="stat-card"><div className="stat-top"><span>Занятия сегодня</span><span className="stat-icon green"><Icon name="calendar" size={19}/></span></div><div className="stat-value">{todayLessons.length}<span>занятия</span></div><div className="stat-description"><span className="mini-dot"/> {doneCount} проведено <span className="muted">· {todayLessons.length-doneCount} впереди</span></div></div><div className="stat-card"><div className="stat-top"><span>Мои группы</span><span className="stat-icon blue"><Icon name="users" size={19}/></span></div><div className="stat-value">{groups.length}<span>групп</span></div><div className="stat-description muted">{groups.reduce((a,g)=>a+g.students,0)} студентов всего</div></div><div className="stat-card"><div className="stat-top"><span>Предметы</span><span className="stat-icon purple"><Icon name="book" size={19}/></span></div><div className="stat-value">8<span>предметов</span></div><div className="stat-description muted">В этом семестре</div></div><div className="stat-card"><div className="stat-top"><span>Посещаемость</span><span className="stat-icon orange"><Icon name="chart" size={19}/></span></div><div className="stat-value">94<span className="percent">%</span><span className="trend">↗ 2%</span></div><div className="stat-description muted">За последние 7 дней</div></div></div>}
 {page==='Сегодня'&&<><div className="dashboard-grid">{schedulePanel}<aside className="right-column"><section><div className="section-heading"><h2>Быстрые действия</h2></div><div className="panel quick-actions"><button onClick={()=>navigate('Журнал')}><span className="action-icon green"><Icon name="journal" size={20}/></span><span><strong>Открыть журнал</strong><small>Оценки и посещаемость</small></span><Icon name="chevron" size={16}/></button><button onClick={()=>openModal('export')}><span className="action-icon blue"><Icon name="download" size={20}/></span><span><strong>Экспорт ведомости</strong><small>Скачать в формате Excel</small></span><Icon name="chevron" size={16}/></button><button onClick={()=>openModal('newGroup')}><span className="action-icon purple"><Icon name="users" size={20}/></span><span><strong>Добавить группу</strong><small>Новая группа студентов</small></span><Icon name="chevron" size={16}/></button></div></section><section className="attention-card"><div className="attention-title"><span className="attention-icon">!</span><h3>Требует внимания</h3><span className="attention-count">2</span></div><button className="attention-item" onClick={()=>{openLesson(lessons.find(l=>l.group==='ПР-31')||lessons[0]);}}><span className="orange-dot"/><span><strong>Не заполнена посещаемость</strong><small>ПР-31 · Разработка веб-приложений</small><span className="attention-date">11 сентября</span></span><Icon name="chevron" size={14}/></button><button className="attention-item" onClick={()=>{setSelectedGroup(groups[0]);openModal('group')}}><span className="orange-dot"/><span><strong>Студенты без оценок</strong><small>ИС-21 · 3 студента за 2 недели</small></span><Icon name="chevron" size={14}/></button></section><section className="tip-card"><span className="tip-icon"><Icon name="leaf" size={21}/></span><h3>Меньше рутины.<br/>Больше преподавания.</h3><p>Выставляйте оценки одним касанием.<br/>Всё остальное мы сохраним за вас.</p><button className="text-link" onClick={()=>openModal('help')}>Как это работает<Icon name="arrow" size={16}/></button><div className="tip-decoration" aria-hidden="true"><span/><span/><span/></div></section><div className="device-note"><Icon name="shield" size={15}/><span>Изменения сохраняются на устройстве</span></div></aside></div><section className="groups-section"><div className="section-heading"><h2>Мои группы<span className="count">{groups.length}</span></h2><button className="text-link" onClick={()=>navigate('Группы')}>Все группы<Icon name="arrow" size={16}/></button></div><div className="groups-grid">{groups.slice(0,4).map(renderGroup)}</div></section></>}
 {page==='Расписание'&&<><div className="toolbar"><label className="search-input"><Icon name="search" size={18}/><input placeholder="Найти занятие или группу" value={query} onChange={e=>setQuery(e.target.value)}/></label><select value={groupFilter} onChange={e=>setGroupFilter(e.target.value)}><option>Все группы</option>{groups.map(g=><option key={g.id}>{g.name}</option>)}</select><Button variant="secondary" onClick={()=>{setDate(TODAY);setWeekOffset(0)}}>Сегодня</Button></div><div className="wide-schedule">{schedulePanel}</div></>}
 {page==='Группы'&&<><div className="toolbar"><label className="search-input"><Icon name="search" size={18}/><input placeholder="Поиск по названию группы" value={query} onChange={e=>setQuery(e.target.value)}/></label><span className="muted">{visibleGroups.length} групп</span></div><div className="groups-grid full-groups">{visibleGroups.map(renderGroup)}</div>{!visibleGroups.length&&<div className="empty-state"><Icon name="search" size={32}/><h3>Группы не найдены</h3><p>Попробуйте другое название.</p></div>}</>}
 {page==='Предметы'&&<><div className="toolbar"><label className="search-input"><Icon name="search" size={18}/><input placeholder="Найти предмет" value={query} onChange={e=>setQuery(e.target.value)}/></label></div><div className="subjects-grid">{(realSubjects.length?realSubjects.map(s=>({name:s.name,grp:s.group_name,hours:s.total_hours,held:s.held_lessons,rem:s.remaining})):subjects.map(s=>({name:s,grp:'',hours:0,held:0,rem:0}))).filter(s=>s.name.toLowerCase().includes(query.toLowerCase())).map((s,i)=><button className="panel subject-card" key={s.name+i} onClick={()=>{navigate('Журнал');setQuery(s.name)}}><span className={'icon-box '+['green','blue','purple','orange'][i%4]}><Icon name="book" size={22}/></span><h3>{s.name}</h3><p>{s.grp||'—'} · {s.hours} часов</p><div className="subject-progress"><span style={{width:(s.hours?Math.round(s.held/s.hours*100):0)+'%'}}/></div><div className="subject-foot"><span>Пройдено {s.hours?Math.round(s.held/s.hours*100):0}%</span><Icon name="arrow" size={17}/></div></button>)}</div>{!(realSubjects.length?realSubjects.map(s=>s.name):subjects).some(n=>n.toLowerCase().includes(query.toLowerCase()))&&<div className="empty-state"><h3>Предмет не найден</h3></div>}</>}
 {page==='Журнал'&&<><div className="toolbar"><label className="search-input"><Icon name="search" size={18}/><input placeholder="Найти предмет или группу" value={query} onChange={e=>setQuery(e.target.value)}/></label><select value={groupFilter} onChange={e=>setGroupFilter(e.target.value)}><option>Все группы</option>{groups.map(g=><option key={g.id}>{g.name}</option>)}</select></div><div className="journal-list">{lessons.filter(l=>(l.title+' '+l.group).toLowerCase().includes(query.toLowerCase())&&(groupFilter==='Все группы'||l.group===groupFilter)).map((l,i)=><div className="journal-entry" key={l.id}><div className="journal-date"><Icon name="calendar" size={15}/>{dateLabel(l.date)}</div>{renderLesson(l,i)}</div>)}</div>{!lessons.some(l=>(l.title+' '+l.group).toLowerCase().includes(query.toLowerCase())&&(groupFilter==='Все группы'||l.group===groupFilter))&&<div className="empty-state"><h3>Занятия не найдены</h3><p>Попробуйте изменить поиск или выбрать другую группу.</p></div>}</>}
 {page==='Отчёты'&&<div className="reports-grid"><section className="panel report-panel"><div className="section-heading"><h2>Посещаемость по группам</h2><span className="muted">Сентябрь</span></div>{groups.map((g,i)=><div className="report-bar" key={g.id}><span>{g.name}</span><div><i style={{width:(98-i*2)+'%'}}/></div><strong>{98-i*2}%</strong></div>)}<p className="report-note">Демонстрационные показатели. Реальная аналитика требует подключения Flask API.</p></section><section className="panel report-panel"><span className="icon-box green"><Icon name="file" size={24}/></span><h2>Ведомость успеваемости</h2><p className="muted">Все сохранённые оценки группы в одном Excel-файле. Удобно для печати и отправки.</p><Button onClick={()=>openModal('export')}><Icon name="download" size={18}/>Сформировать ведомость</Button></section></div>}
 {page==='Настройки'&&<div className="settings-layout"><form className="panel settings-card" onSubmit={e=>{e.preventDefault();const name=String(new FormData(e.currentTarget).get('name')).trim();if(!name)return;const next={name,initials:name.split(' ').slice(0,2).map(n=>n[0]).join('')};setProfile(next);saveLocal('profile',next);notify('Профиль сохранён')}}><h2>Профиль преподавателя</h2><p>Как к вам обращаться в приложении</p><label className="form-field">Имя и отчество<input name="name" defaultValue={profile.name} required maxLength={60}/></label><Button type="submit">Сохранить изменения</Button></form><section className="panel settings-card"><h2>Интерфейс</h2><div className="setting-row"><div><strong>Компактный журнал</strong><p>Больше студентов на одном экране</p></div><button className={'toggle '+(compact?'on':'')} role="switch" aria-checked={compact} aria-label="Компактный журнал" onClick={()=>{setCompact(!compact);saveLocal('compact',!compact)}}><span/></button></div><div className="setting-row"><div><strong>Лёгкое оформление</strong><p>Без анимаций и фоновых изображений</p></div><span className="status status-done">Включено</span></div></section><section className="panel settings-card"><h2>Данные и резервная копия</h2><p>Сейчас работает демонстрационная версия. Изменения хранятся только в этом браузере, отдельно от lessons.db.</p><Button variant="secondary" onClick={()=>{if(apiOk){postBackup().then(()=>notify('Резервная копия создана на сервере')).catch(()=>{downloadBlob(new Blob([JSON.stringify({version:1,lessons,groups,grades,profile},null,2)],{type:'application/json'}),'teachhelper-demo-backup.json');notify('Копия демоданных подготовлена')})}else{downloadBlob(new Blob([JSON.stringify({version:1,lessons,groups,grades,profile},null,2)],{type:'application/json'}),'teachhelper-demo-backup.json');notify('Копия демоданных подготовлена')}}}><Icon name="download" size={17}/>{apiOk?'Резервная копия (сервер)':'Скачать копию демоданных'}</Button><div className="info-note"><Icon name="shield" size={18}/><span>Схема SQLite не изменена. Для работы в APK необходимо подключить исходный Flask API и проверить Android WebView.</span></div></section></div>}
 <footer className="page-footer"><span>TeachHelper <span className="version">· Лёгкий журнал преподавателя</span></span><span><span className="green-dot"/>Демо-режим · Данные на устройстве</span></footer>
 </main></div>
 <nav className="bottom-nav">{[nav[0],nav[1],nav[4],nav[2]].map(n=><button className={page===n.label?'active':''} key={n.label} onClick={()=>navigate(n.label)}><Icon name={n.icon} size={21}/><span>{n.label}</span></button>)}<button className={menu?'active':''} onClick={()=>setMenu(!menu)}><Icon name="menu" size={21}/><span>Ещё</span></button></nav>
 {toast&&<div className="toast" role="status"><Icon name="check-circle" size={19}/>{toast}<button aria-label="Закрыть уведомление" onClick={()=>setToast('')}><Icon name="close" size={16}/></button></div>}
 {modal&&<div className={'modal-backdrop '+(modal==='lesson'?'lesson-backdrop':'')} onClick={e=>{if(e.target===e.currentTarget)setModal(null)}}><div className={'modal '+(modal==='lesson'?'lesson-modal':'')+(modal==='group'?' group-modal':'')} role="dialog" aria-modal="true" aria-labelledby="modal-title" ref={modalRef}><div className="modal-header"><div><span className="eyebrow">TEACHHELPER</span><h2 id="modal-title">{modal==='lesson'?selectedLesson?.title:modal==='newLesson'?'Начать занятие':modal==='newGroup'?'Новая группа':modal==='export'?'Экспорт ведомости':modal==='help'?'Ваш лёгкий журнал':modal==='notifications'?'Уведомления':modal==='group'?'Группа '+selectedGroup?.name:'Выберите дату'}</h2></div><button className="icon-button" onClick={()=>setModal(null)} aria-label="Закрыть окно"><Icon name="close" size={22}/></button></div>
 {modal==='lesson'&&selectedLesson&&<><div className="lesson-modal-subtitle"><span className="group-tag"><Icon name="users" size={14}/>{selectedLesson.group}</span><span>{dateLabel(selectedLesson.date)} · {selectedLesson.start}–{selectedLesson.end}</span></div><div className="attendance-toolbar"><label className="search-input"><Icon name="search" size={17}/><input value={studentQuery} onChange={e=>setStudentQuery(e.target.value)} placeholder="Найти студента"/></label><button className="text-link" onClick={()=>{const next={...grades};const bulk:{student_id:number;grade:string}[]=[];lessonStudents.forEach(s=>{if(!next[selectedLesson.id+':'+s.name]||next[selectedLesson.id+':'+s.name]==='—'){next[selectedLesson.id+':'+s.name]='0';if(s.id>0)bulk.push({student_id:s.id,grade:'0'})}});setGrades(next);saveLocal('grades',next);if(apiOk&&selectedLesson.id&&bulk.length)postAttendanceBulk(selectedLesson.id,bulk).catch(()=>{});notify('Присутствие отмечено')}}><Icon name="check" size={17}/>Все присутствуют</button></div><div className="grade-hint"><Icon name="help" size={15}/><span>Нажмите на оценку, чтобы изменить: — → 0 → 5 → 4 → 3 → 2. <b>0 — присутствует, Н — отсутствует.</b></span></div><div className="student-list">{lessonStudents.filter(s=>s.name.toLowerCase().includes(studentQuery.toLowerCase())).map((s,i)=>{const grade=grades[selectedLesson.id+':'+s.name]||'—';return <div className="student-row" key={s.name+s.id}><span className="student-number">{i+1}</span><span className="student-name">{s.name.split(' ')[0]}<small>{s.name.split(' ').slice(1).join(' ')}</small></span><button className={'absence-button '+(grade==='Н'?'absent':'')} aria-label={'Отсутствие: '+s.name} onClick={()=>saveGrade(s.name,grade==='Н'?'—':'Н')}>Н</button><button className={'grade-button grade-'+grade} aria-label={'Оценка '+s.name+': '+grade+'. Изменить'} onClick={()=>cycleGrade(s.name,1)} onContextMenu={e=>{e.preventDefault();cycleGrade(s.name,-1)}}>{grade==='0'?<Icon name="check" size={19}/>:grade}</button></div>})}</div><div className="modal-footer"><span className="autosave"><Icon name="check-circle" size={15}/>Сохранено на устройстве</span><Button onClick={()=>{persistLessons(lessons.map(l=>l.id===selectedLesson.id?{...l,status:'done'}:l));setModal(null);notify('Занятие завершено. Оценки сохранены.')}}><Icon name="check" size={17}/>Завершить занятие</Button></div></>}
 {modal==='newLesson'&&<form className="modal-form" onSubmit={createLesson}><p className="muted">Выберите группу и предмет, чтобы перейти к журналу.</p><label className="form-field">Группа<select name="group">{groups.map(g=><option key={g.id}>{g.name}</option>)}</select></label><label className="form-field">Предмет<select name="subject">{(realSubjects.length?realSubjects.map(s=>s.name):subjects).map(s=><option key={s}>{s}</option>)}</select></label><div className="form-grid"><label className="form-field">Дата<input name="date" type="date" defaultValue={date>TODAY?TODAY:date} max={TODAY} required/></label><label className="form-field">Кабинет<input name="room" placeholder="Например, 204"/></label><label className="form-field">Начало<input type="time" name="start" defaultValue="10:10" required/></label><label className="form-field">Окончание<input type="time" name="end" defaultValue="11:40" required/></label></div><label className="form-field">Тип занятия<select name="type"><option>Практическое занятие</option><option>Лекция</option><option>Лабораторная работа</option></select></label>{formError&&<p className="form-error" role="alert">{formError}</p>}<Button type="submit" className="full-width"><Icon name="play" size={17}/>Начать занятие</Button></form>}
 {modal==='newGroup'&&<form className="modal-form" onSubmit={createGroup}><p className="muted">Создайте группу для ведения журнала.</p><label className="form-field">Название группы<input name="name" placeholder="Например, ИС-23" maxLength={24} required/></label><label className="form-field">Специальность<input name="specialty" placeholder="Информационные системы" required/></label><label className="form-field">Курс<select name="course">{[1,2,3,4,5].map(n=><option key={n}>{n}</option>)}</select></label>{formError&&<p className="form-error" role="alert">{formError}</p>}<Button type="submit" className="full-width"><Icon name="plus" size={18}/>Создать группу</Button></form>}
 {modal==='export'&&<div className="modal-form"><div className="export-preview"><span className="icon-box green"><Icon name="file" size={27}/></span><div><strong>Ведомость успеваемости</strong><p>Microsoft Excel · .xlsx</p></div></div><label className="form-field">Группа<select value={exportGroup} onChange={e=>setExportGroup(e.target.value)}>{groups.map(g=><option key={g.id}>{g.name}</option>)}</select></label><label className="form-field">Включить занятия по дату<input type="date" value={exportDate} onChange={e=>setExportDate(e.target.value)} required/></label><p className="info-note"><Icon name="shield" size={20}/><span>В файл попадут студенты выбранной группы и оценки, сохранённые в демоверсии.</span></p><Button className="full-width" onClick={exportReport}><Icon name="download" size={18}/>Скачать ведомость</Button></div>}
 {modal==='help'&&<div className="help-content"><p>Самое важное — всегда под рукой. Три простых шага к заполненному журналу.</p>{[{icon:'calendar',title:'1. Откройте занятие',text:'Выберите занятие в расписании или нажмите «Начать занятие».'},{icon:'journal',title:'2. Отметьте студентов',text:'Нажимайте на оценку для переключения. 0 означает присутствие, Н — отсутствие. Изменения сохраняются автоматически.'},{icon:'download',title:'3. Поделитесь результатом',text:'Сформируйте ведомость группы и скачайте настоящий Excel-файл.'}].map(s=><div className="help-step" key={s.title}><span className="icon-box green"><Icon name={s.icon as IconName}/></span><div><h3>{s.title}</h3><p>{s.text}</p></div></div>)}<div className="info-note"><Icon name="help" size={20}/><span>Это интерактивная демоверсия нового интерфейса. Рабочая база репозитория не подключена и не изменена. Совместимость APK с Android 7 нужно проверить на устройстве.</span></div><Button className="full-width" onClick={()=>setModal(null)}>Всё понятно</Button></div>}
 {modal==='notifications'&&<div className="notifications-content"><span className="status status-upcoming">Демонстрационные уведомления</span><button onClick={()=>{setSelectedGroup(groups[0]);setModal('group')}}><span className="icon-box orange"><Icon name="users"/></span><div><h3>Обратите внимание на ИС-21</h3><p>У 3 студентов нет оценок за последние две недели.</p><small>Сегодня, 09:00</small></div><Icon name="chevron" size={16}/></button><div className="notification-info"><span className="icon-box green"><Icon name="shield"/></span><div><h3>Ваши изменения сохранены</h3><p>Локальное сохранение включено. Данные доступны в этом браузере.</p></div></div></div>}
 {modal==='calendar'&&<div className="calendar-content"><div className="calendar-heading"><button className="icon-button" aria-label="Предыдущий месяц" onClick={()=>setCalendarMonth(calendarMonth-1)}><Icon name="left"/></button><h3>{new Date(2026,calendarMonth,1).toLocaleDateString('ru-RU',{month:'long',year:'numeric'})}</h3><button className="icon-button" aria-label="Следующий месяц" onClick={()=>setCalendarMonth(calendarMonth+1)}><Icon name="chevron"/></button></div><div className="month-grid">{weekdays.map(w=><span className="month-weekday" key={w}>{w}</span>)}{Array.from({length:(new Date(2026,calendarMonth,1).getDay()+6)%7},(_,i)=><span key={'blank'+i}/>)}{Array.from({length:new Date(2026,calendarMonth+1,0).getDate()},(_,i)=>{const d=isoDate(new Date(2026,calendarMonth,i+1));return <button key={d} className={d===date?'selected':''} onClick={()=>{setDate(d);const diff=Math.round((new Date(d+'T12:00:00').getTime()-new Date(TODAY+'T12:00:00').getTime())/86400000);setWeekOffset(Math.floor(diff/7));setModal(null)}}>{i+1}{lessons.some(l=>l.date===d)&&<i/>}</button>})}</div><Button variant="secondary" className="full-width" onClick={()=>{setDate(TODAY);setWeekOffset(0);setModal(null)}}>Сегодня, 14 сентября</Button></div>}
 {modal==='group'&&selectedGroup&&<div className="group-content"><p className="muted">{selectedGroup.course}</p><div className="group-summary"><span><Icon name="users" size={18}/>{selectedGroup.students} студента</span><span><Icon name="book" size={18}/>{selectedGroup.subjects} предмета</span></div><div className="group-modal-actions"><Button onClick={()=>{setModal(null);navigate('Журнал');setGroupFilter(selectedGroup.name)}}><Icon name="journal" size={17}/>Открыть журнал</Button><Button variant="secondary" onClick={()=>{setExportGroup(selectedGroup.name);setModal('export')}}><Icon name="download" size={17}/>Ведомость</Button></div><h3 className="students-heading">Студенты группы</h3><label className="search-input"><Icon name="search" size={17}/><input placeholder="Поиск студента" value={studentQuery} onChange={e=>setStudentQuery(e.target.value)}/></label><div className="group-students">{studentNames.slice(0,selectedGroup.students).filter(s=>s.toLowerCase().includes(studentQuery.toLowerCase())).map((s,i)=><div key={s}><span className="student-number">{i+1}</span><span>{s}</span><span className="status status-done">Обучается</span></div>)}{selectedGroup.students===0&&<div className="empty-state"><p>В этой группе пока нет студентов.<br/>Добавление списков будет доступно после подключения API.</p></div>}</div></div>}
 </div></div>}
 </div>
}
